# Site settings
title: JasonAnton.com
email: admin@jasonanton.com
description: > # this means to ignore newlines until "baseurl:"
  This is quite simply--and modestly--the absolute best site in the entire world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jasonanton.com" # the base hostname & protocol for your site
twitter_username: revjtanton
github_username:  revjtanton

# Build settings
markdown: kramdown

# Collections
collections:
    vr:
        output: true
  
# Gems
gems:
  - jekyll-sitemap